### PR TITLE
.NET Core updates

### PR DESCRIPTION
**Pull request by ghost**
- Update HtmlGenerator project to use netstandard1.0 instead of dnxcore50 etc.
- Refactor the project path from src/src/HtmlGenerator to src/HtmlGenerator
- Update HtmlGeneratorMeta project to xproj.
- Ability to provide directory from command line argument.
- Ignore project.lock.json file from git repo.
- Update solution and global.json.
- Configured AppVeyor CI for Windows: e.g. https://ci.appveyor.com/project/jasonwilliams200OK/html-generator/build/1.0.9
  - Ability to save artifacts on each build job: e.g. https://ci.appveyor.com/project/jasonwilliams200OK/html-generator/build/1.0.6/job/tiuap6ppghstgint/artifacts
- Configured Travis CI for Ubuntu and macOS: e.g. https://travis-ci.org/jasonwilliams200OK/html-generator/builds/147080850
- Added badges in README. To enable those badges, please logon to AppVeyor and Travis with your GitHub account and add the repo from the list.

### CODE REVIEW

**Comment by hughbe** [comment]
Thanks so much for this @jasonwilliams200OK

I'm travelling around Europe ATM without a laptop so can't build this locally. I assume you've built everything but a simple confirmation would be great!

Meanwhile I'll take a look at the PR in the next few days when I have time

Thanks again

**Comment by ghost** [comment]
@hughbe, yup I validated the changes on Windows, Unix and configured CI to verify.

**Comment by hughbe** [comment]
I've come back, taken a look - it all looks good! Thanks

**Comment by ghost** [comment]
@hughbe, thanks! Could you please sign in with your GitHub on AppVeyor and add this project so this https://ci.appveyor.com/project/hughbe/html-generator/branch/master light up? Also, on TravisCI https://travis-ci.org/hughbe/html-generator for Unix builds. :)

**Comment by hughbe** [comment]
Thanks - all done!

**Pull request merged**
